### ISSUE TITLE
duplicates are not allowed in a repeater

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#134]
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.13-build.2250+sha.08793a6/ngRepeat/dupes?p0=guess%20in%20guesses&p1=string%3As
    at Error (native)
    at http://localhost:8080/components/angular/angular.min.js:6:473
    at http://localhost:8080/components/angular/angular.min.js:185:179
    at Object.fn (http://localhost:8080/components/angular/angular.min.js:100:35)
    at h.$digest (http://localhost:8080/components/angular/angular.min.js:100:467)
    at h.$apply (http://localhost:8080/components/angular/angular.min.js:103:264)
    at SocketNamespace.<anonymous> (http://localhost:8080/js/services.js:14:20)
    at SocketNamespace.EventEmitter.emit [as $emit](http://localhost:8080/socket.io/socket.io.js:638:22)
    at SocketNamespace.onPacket (http://localhost:8080/socket.io/socket.io.js:2248:20)
    at Socket.onPacket (http://localhost:8080/socket.io/socket.io.js:1930:30)

**Comment by ulrichson** [comment]
see #132 

http://stackoverflow.com/questions/19952950/dynamically-reloading-ng-repeat-data-in-the-dom suggests to call `push()` for a new array item.
