### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#37]
not sure if your refactoring is already done, but there are some test failures:

<quote>

  0 passing (3ms)
  1 failing

  1) Hangman "before all" hook:
     TypeError: object is not a function
      at Context.<anonymous> (/home/bonomat/workspace/nodejs/hangman/test/hangman.test.coffee:10:22)
      at Hook.Runnable.run (/home/bonomat/workspace/nodejs/hangman/node_modules/mocha/lib/runnable.js:194:15)
      at next (/home/bonomat/workspace/nodejs/hangman/node_modules/mocha/lib/runner.js:249:10)
      at Object._onImmediate (/home/bonomat/workspace/nodejs/hangman/node_modules/mocha/lib/runner.js:261:5)
      at processImmediate [as _immediateCallback](timers.js:330:15)

</quote>

**Comment by holzeis** [comment]
yap, i forgot to adjust the server side unit tests.
i changed how the hangman class is exported, thus it must be instantiated differently.
