### ISSUE TITLE
socket.io exception

### ISSUE THREAD

**Issue by ulrichson** [bitbetwin/bitbetwin#96]
Calling landingpage causes an exception, although landingpage has no socket.io included.

```
Error: Bad Request
  at SendStream.error (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/send/lib/send.js:145:16)
  at SendStream.pipe (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/send/lib/send.js:298:31)
  at Object.staticMiddleware [as handle] (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/static.js:84:8)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.methodOverride [as handle] (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:49:5)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at multipart (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
  at /Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
  at urlencoded (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
  at /Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
  at json (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
  at Object.bodyParser [as handle] (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at /Users/ulrich/Projects/Node/hangman/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:54:18
  at ConnectFileCache.loadFile (/Users/ulrich/Projects/Node/hangman/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:63:16)
  at ConnectFileCache.middleware (/Users/ulrich/Projects/Node/hangman/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:48:19)
  at Object.handle (/Users/ulrich/Projects/Node/hangman/node_modules/connect-assets/node_modules/connect-file-cache/lib/cache.js:4:61)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.expressInit [as handle] (/Users/ulrich/Projects/Node/hangman/node_modules/express/lib/middleware.js:30:5)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.query [as handle] (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
  at next (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Function.app.handle (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/proto.js:198:3)
  at Server.app (/Users/ulrich/Projects/Node/hangman/node_modules/express/node_modules/connect/lib/connect.js:65:37)
  at Manager.handleRequest (/Users/ulrich/Projects/Node/hangman/node_modules/socket.io/lib/manager.js:565:28)
  at Server.<anonymous> (/Users/ulrich/Projects/Node/hangman/node_modules/socket.io/lib/manager.js:119:10)
  at Server.EventEmitter.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2108:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1966:22)
  at TCP.onread (net.js:525:27)
```

**Comment by holzeis** [comment]
hey, just called the landing page on the master and got no exception.
