### ISSUE TITLE
game view fails at loading

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#99]
TypeError: undefined is not a function
    at v (http://localhost:8080/components/angular-route/angular-route.min.js:6:311)
    at g.$broadcast (http://localhost:8080/components/angular/angular.min.js:102:324)
    at http://localhost:8080/components/angular-route/angular-route.min.js:11:179
    at C (http://localhost:8080/components/angular/angular.min.js:91:121)
    at C (http://localhost:8080/components/angular/angular.min.js:91:121)
    at http://localhost:8080/components/angular/angular.min.js:92:288
    at g.$eval (http://localhost:8080/components/angular/angular.min.js:100:198)
    at g.$digest (http://localhost:8080/components/angular/angular.min.js:98:82)
    at g.$apply (http://localhost:8080/components/angular/angular.min.js:101:12)
    at g (http://localhost:8080/components/angular/angular.min.js:66:321)

**Comment by holzeis** [comment]
used outdated angular js version.
bower install fixes the issue
